insert into Seasons (year) values (2008);
insert into Seasons (year) values (2009);
insert into Seasons (year) values (2010);
insert into Seasons (year) values (2011);
insert into Seasons (year) values (2012);
insert into Seasons (year) values (2013);
insert into Seasons (year) values (2014);
insert into Seasons (year) values (2015);

insert into Teams (name) values ('McLaren');
insert into Teams (name) values ('Ferrari');
insert into Teams (name) values ('Brawn GP');
insert into Teams (name) values ('Red Bull Racing');
insert into Teams (name) values ('Lotus F1');
insert into Teams (name) values ('Mercedes');

insert into Racers (name, surname) values ('Lewis','Hamilton');
insert into Racers (name, surname) values ('Felipe','Massa');
insert into Racers (name, surname) values ('Kimi','Raikkonen');
insert into Racers (name, surname) values ('Jenson','Button');
insert into Racers (name, surname) values ('Sebastian','Vettel');
insert into Racers (name, surname) values ('Rubens','Barichello');
insert into Racers (name, surname) values ('Fernando','Alonso');
insert into Racers (name, surname) values ('Mark','Webber');
insert into Racers (name, surname) values ('Nico','Rosberg');
insert into Racers (name, surname) values ('Daniel','Ricciardo');

insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (1, 1, 1, 1);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (2, 2, 2, 1);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (3, 3, 2, 1);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (1, 4, 3, 2);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (2, 5, 4, 2);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (3, 6, 3, 2);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (1, 5, 4, 3);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (2, 7, 2, 3);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (3, 8, 4, 3);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (1, 5, 4, 4);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (2, 4, 1, 4);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (3, 8, 4, 4);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (1, 5, 4, 5);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (2, 7, 2, 5);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (3, 3, 5, 5);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (1, 5, 4, 6);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (2, 7, 2, 6);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (3, 8, 4, 6);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (1, 1, 6, 7);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (2, 9, 6, 7);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (3, 10, 4, 7);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (1, 1, 6, 8);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (2, 9, 6, 8);
insert into SEASON_RESULTS (position, racer_id, team_id, season_id) values (3, 5, 2, 8);